backend:
  name: git-gateway
  branch: master

media_folder: '/static/announcements'
public_folder: '/announcements'

collections:
  - name: 'announcement'
    label: 'Announcement'
    folder: 'static/announcements'
    create: true
    slug: '{{slug}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - {
          label: 'Publish Date',
          name: 'date',
          widget: 'date',
          timeFormat: false,
          format: 'DD MM YYYY',
        }
      - { label: 'Description', name: 'description', widget: 'text' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
