backend:
  name: git-gateway
  branch: master

media_folder: "static/updates"
public_folder: "/updates"

collections:
  - name: "update"
    label: "Update"
    folder: "static/updates"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}