backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

collections:
  - name: "update"
    label: "Update"
    folder: "static/uploads"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}